SELECT cantMundialesDirigidos.nombre_apellido, cantMundialesDirigidos.cantidad
FROM cantMundialesDirigidos
WHERE cantMundialesDirigidos.cantidad = (SELECT MAX(cantMundialesDirigidos.cantidad) FROM cantMundialesDirigidos)